output:
  format: tab

linters-settings:
  tagliatelle:
    case:
      rules:
        json: snake
        yaml: kebab
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-occurrences: 3
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: go/src/FoodOrdering
  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks: 
              - argument
              - case
              - condition
              - operation
              - return
              - assign
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  misspell:
    locale: US
    ignore-words:
      - cancelled
  exhaustive:
    default-signifies-exhaustive: true
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: true # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: true # don't require nolint directives to be specific about which linter is being skipped

linters:
  disable-all: true
  # These are all the linters included in 1.45.2, except for a few we decided not to use (see below)
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - deadcode
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - ifshort
    - importas
    - ineffassign
    - ireturn
    - lll
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - wrapcheck

  # This section is just to document linters that were available but decided not to use
  #    # Deprecated linters
  #    - golint
  #    - maligned
  #    - interfacer
  #    - scopelint
  #
  #    # Deemed unuseful
  #    - nlreturn # stylistic with minimal benefit
  #    - wsl # stylistic with minimal benefit
  #    - whitespace # stylistic with minimal benefit
  #    - varnamelen # not enough contextual awareness
  #    - exhaustivestruct # not usually useful
  #    - gci # buggy, complained about GitHub imports

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - dupl
        - gochecknoglobals
        - containedctx
        - maintidx
    - path: '(.+)_gen\.go'
      linters:
        - gomnd
        - funlen
        - dupl
        - gochecknoglobals
        - containedctx
        - maintidx
        - godot
        - goerr113
        - wrapcheck
#run:
  #skip-dirs: