name: Linter and Test Cases

on:
  push:
  pull_request:
    branches: [dev, main, master]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      # run go lint
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
          args: --timeout 3m0s
          skip-cache: false
          skip-pkg-cache: false
          skip-build-cache: false
          
      # run unit test
      - uses: actions/checkout@v3
      - run: go test ./...
